### ISSUE TITLE
Repo should have .gitattributes to exclude tests with PHP errors

### ISSUE THREAD

**Issue by ondrejmirtes** [php-parallel-lint/PHP-Parallel-Lint#11]
^^ What the title says :) Basically this would suffice:

```
/tests export-ignore
```

**Comment by jrfnl** [comment]
See #13

**Comment by grogy** [comment]
Yes! Thank you boys, great idea and perfect PR from @jrfnl

**Comment by jrfnl** [comment]
... and girls ?

**Comment by grogy** [comment]
Oh my god.. I am so sorry :-)

**Comment by jrfnl** [comment]
@grogy In that case: you're forgiven :smile:
