### ISSUE TITLE
Offer this package as a GitHub Action

### ISSUE THREAD

**Issue by bkuhl** [php-parallel-lint/PHP-Parallel-Lint#111]
It would be excellent if this package could be updated to also offer this linting as a GitHub action.

**Comment by jrfnl** [comment]
@bkuhl Are you aware that you can already install the tool via the `setup-php` action ?
See: https://github.com/shivammathur/setup-php#wrench-tools-support

I'm not sure creating an action would really make much sense as the user would always still need to provide a number of settings (like what to scan, what to exclude etc) and PHP still would need to be installed (either ahead of time or via the action), so IMO using the `tools` setting in the `setup-php` action already is an optimized way this tool can be used in GH actions.

**Comment by bkuhl** [comment]
Yep, that'll work.  Thanks!
