### ISSUE TITLE
How to hide progress?

### ISSUE THREAD

**Issue by realtebo** [php-parallel-lint/PHP-Parallel-Lint#143]
I'd like to hide progress (dots and 'X'es and percentages) to have a more clean output to be parsed by a CI/CD tool.

I cannot find the option to hide progress.

I'd like only file names of files with syntax erros

**Comment by jrfnl** [comment]
You mean `--no-progress` ?

Ref: https://github.com/php-parallel-lint/PHP-Parallel-Lint#command-line-options

**Comment by realtebo** [comment]
Sorry, my fault
