### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by danepowell** [php-parallel-lint/PHP-Parallel-Lint#20]
The last stable release was a couple months ago, can we get a new one?

We'd like to switch from jakob-onderka to this fork but can't do so until there's a new stable release, since we need the following fixes that are only in master:
- https://github.com/php-parallel-lint/PHP-Parallel-Lint/commit/de81f0abc17444d3070e2c0623950ebf434f3361#diff-32f5d7dbf80a3aeafb22a44ccda60465
- https://github.com/php-parallel-lint/PHP-Parallel-Lint/pull/2

This would also reduce your support burden, since it seems like other people are affected by issues in master and opening issues like https://github.com/php-parallel-lint/PHP-Parallel-Lint/issues/19

**Comment by grogy** [comment]
Hello, new release [is comming](https://github.com/php-parallel-lint/PHP-Parallel-Lint/releases/tag/v1.2.0) :-)
