### ISSUE TITLE
PHPStan

### ISSUE THREAD

**Issue by grogy** [php-parallel-lint/PHP-Parallel-Lint#27]
Possibly run PHPStan in CI

Original in https://github.com/grogy/PHP-Parallel-Lint/issues/4 thanks to @szepeviktor

**Comment by grogy** [comment]
First draft for implementation is here:
- branch: https://github.com/php-parallel-lint/PHP-Parallel-Lint/tree/phpstan
- CI tests in 7.4: https://travis-ci.org/github/php-parallel-lint/PHP-Parallel-Lint/builds/676244307

**Comment by szepeviktor** [comment]
See my PR please https://github.com/php-parallel-lint/PHP-Parallel-Lint/issues/27

**Comment by szepeviktor** [comment]
Level 4 is the lowest on error-free software.

Could you correct these https://travis-ci.org/github/php-parallel-lint/PHP-Parallel-Lint/jobs/676249045#L267-L320 or should I send another PR for that?

**Comment by grogy** [comment]
When you have a time, please send PR :-) Level 4 will be great

**Comment by szepeviktor** [comment]
@grogy Done in #29, please review it.

**Comment by grogy** [comment]
Thank you, merged :+1:
