### ISSUE TITLE
PHIVE

### ISSUE THREAD

**Issue by grogy** [php-parallel-lint/PHP-Parallel-Lint#28]
Please consider releasing the PHAR file on PHIVE https://phar.io/

Original from https://github.com/grogy/PHP-Parallel-Lint/issues/5 thanks to @szepeviktor

**Comment by grogy** [comment]
PHAR file is now created as part of build. Now is created version 1.3.0 https://github.com/php-parallel-lint/PHP-Parallel-Lint/releases/tag/v1.3.0

There is a link for a downloading

**Comment by szepeviktor** [comment]
Thank you.
Please consider signing and uploading the signature 👉 so PHIVE can install it.

**Comment by jrfnl** [comment]
Just had a quick look: the signature creation and upload could be added to the release workflow for GH Actions.

This would require the prerequisites regarding the GPG key generation and registration to be filled prior to it though. The user email address for identification would probably need to be added to the repos secrets so it can be safely used in the workflow.

Ref: https://phar.io/howto/sign-and-upload-to-github.html
