### ISSUE TITLE
Unexpected end of file with anonymous function

### ISSUE THREAD

**Issue by Pablo-Lilao** [php-parallel-lint/PHP-Parallel-Lint#31]
**Describe the bug**
When parallel-lint analyses a php file with an anonymous function it throws an error. 

**To reproduce**
[test.zip](https://github.com/php-parallel-lint/PHP-Parallel-Lint/files/4588653/test.zip)

**Expected behavior**
Parallel-lint analyses the source file without throwing any error.

**Screenshots**
![Parallel-lint_error](https://user-images.githubusercontent.com/63185445/81213226-5b8d9480-8fd6-11ea-8ece-ee241bb66dfb.jpg)

**Comment by jrfnl** [comment]
@Pablo-Lilao That's because your code **has** a parse error.

Your code:
```php
function ()
{
    $a= 10;
}
```

Should be fixed to:
```php
function ()
{
    $a= 10;
};
```

Take note of the semi-colon after the curly close brace of the closure. That was missing from your code sample and is the cause of the parse error.

**Comment by Pablo-Lilao** [comment]
Indeed, that was the issue.
