### ISSUE TITLE
Make box config compatible with humbug/box

### ISSUE THREAD

**Issue by mwgamble** [php-parallel-lint/PHP-Parallel-Lint#36]
The box package maintained in the humbug organisation is the newest version of box (known as box3) being maintained by the community:

https://github.com/humbug/box

It would be great if we could get a new release that contained a box config file compatible with box3.

Alternatively, perhaps the maintainers of this package could provide a phar (hopefully with the php-console-highlighter package included) in the github releases section.

**Comment by grogy** [comment]
Thank you. It can solve #28 Can you prepare config as pull request?

**Comment by mwgamble** [comment]
Done, see #39
