### ISSUE TITLE
Switch to using GH Actions ?

### ISSUE THREAD

**Issue by jrfnl** [php-parallel-lint/PHP-Parallel-Lint#44]
As Travis for open source had died a quiet dead, should the CI building be switched over to GH Actions ?
I'd be happy to have a go at that (for this repo and some of the others in the organisation) if you think it's a good idea.

Also related: https://github.com/php-parallel-lint/PHP-Parallel-Lint/issues/42#issuecomment-751907195

**Comment by grogy** [comment]
I agree with moving. More projects (etc Symfony) moving - https://github.com/symfony/symfony/actions

When you or somebody have a time, I like merge PR.
