### ISSUE TITLE
New version - 1.3

### ISSUE THREAD

**Issue by grogy** [php-parallel-lint/PHP-Parallel-Lint#56]
How writes @glensc in https://github.com/php-parallel-lint/PHP-Parallel-Lint/pull/51#issuecomment-810625112 - its time for the new version. For the first we have new changes, for second in PRs are bigger structure changes and for last is a year ago of the last version

Who can - please test current master

**Comment by glensc** [comment]
where did this disappear? long vacation?

also, I submitted changelog fix:
- https://github.com/php-parallel-lint/PHP-Parallel-Lint/pull/57

**Comment by grogy** [comment]
Thank you. Some free days with family ;-)

I tested the current master (phar output) with PHP 5.4, 7.4, and 8.0. All looks OK

**Comment by grogy** [comment]
Done https://github.com/php-parallel-lint/PHP-Parallel-Lint/releases/tag/v1.3.0

**Comment by glensc** [comment]
Cheers!
