### ISSUE TITLE
Suggestion to add the --show-deprecated option to help/docs

### ISSUE THREAD

**Issue by stronk7** [php-parallel-lint/PHP-Parallel-Lint#81]
Hi,

unless I'm missing something, the `--show-deprecated` option is not documented in readme / cli help. And it really would be useful to have it present there. It took some time to me to see if it was supported or no when it's important enough, IMO.

For your consideration, thanks for the estupendo linter!

Ciao :-)

**Comment by jrfnl** [comment]
Looks like it also doesn't show when using the `-h` argument on the command-line.

**Comment by jrfnl** [comment]
PR #84 should address this.
