### ISSUE TITLE
Suggestion: always display the application version in console

### ISSUE THREAD

**Issue by jrfnl** [php-parallel-lint/PHP-Parallel-Lint#95]
Currently when running the application, the first line of the console output looks like this:
```
PHP 8.1.2 | 10 parallel jobs
```

I'd like to suggest including the name and version of this application in this line, like so:
```
PHP-Parallel-Lint 1.3.1 | PHP 8.1.2 | 10 parallel jobs
```

Opinions ?

**Comment by mfn** [comment]
Makes sense and good behaviour. Might it break scripts parsing the output? IDE integrations or something? … 🤷🏼

**Comment by jrfnl** [comment]
> Might it break scripts parsing the output? IDE integrations or something? … 🤷🏼

Good question, though I don't think that will really be an issue.
IDE integrations and such will normally use a different report format, like `--checkstyle` or `--json`, not the plain text console output.
